version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  bot:
    build: .
    container_name: bot
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env.dist
    command: ["python", "main.py", "db/init_db.py"]

volumes:
  mongo-data: